// Frontend-only contract tests with a mock DOM/host. These do not prove Unreal.
const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../Resources/native_showcase.html'),'utf8');
const script=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');
function state(overrides={}){return {generation:'1',scope:'scope1',sequence:'1',hostSeconds:12.5,engineVersion:'test-fixture',canRestore:false,selectedActorIds:['opaque-a'],actors:[{id:'opaque-a',label:'<img src=x onerror=bad()>',class:'Actor',selected:true,editable:true,transform:{location:[0,0,0],rotation:[0,0,0],scale:[1,1,1]}}],assets:[],...overrides};}
function setup(){
 const elements=new Map(),events={},subscriptions={},calls=[];
 class Element{constructor(){this.children=[];this.value='';this.disabled=false;}set id(v){this._id=v;elements.set(v,this);}get id(){return this._id;}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}setAttribute(){}set innerHTML(v){throw Error('Unsafe raw HTML write: '+v);}}
 const document={createElement:()=>new Element(),getElementById(id){if(!elements.has(id))elements.set(id,new Element());return elements.get(id);}};
 let reply=state();
 const context=vm.createContext({document,addEventListener:(n,f)=>events[n]=f,auroraview:{on:(n,f)=>subscriptions[n]=f,call:async(method,params)=>{calls.push({method,params});return typeof reply==='function'?reply(method,params):reply;}},console});
 new vm.Script(script,{filename:'actual-native_showcase.html'}).runInContext(context);
 return {elements,events,subscriptions,calls,setReply:v=>reply=v,ready:async()=>{events.auroraviewready();await flush();}};
}
async function flush(){await new Promise(r=>setImmediate(r));}
test('actual inspector subscribes via existing Core API and renders safe text',async()=>{const h=setup();await h.ready();assert.equal(h.calls[0].method,'showcase.subscribe');assert.equal(h.elements.get('connection').textContent,'HOST CONNECTED');assert.equal(h.elements.get('selection').children[0].children[0].textContent,'<img src=x onerror=bad()>');assert.equal(h.elements.get('apply').disabled,false);});
test('host push does not silently overwrite an edit or its expected transform',async()=>{const h=setup();await h.ready();h.elements.get('location0').value='75';h.elements.get('location0').oninput();const changed=state();changed.actors[0].transform.location=[20,0,0];h.subscriptions['showcase.state'](changed);assert.equal(h.elements.get('location0').value,'75');h.setReply(()=>null);h.elements.get('apply').onclick();await flush();const call=h.calls.at(-1);assert.equal(call.method,'showcase.setTransform');assert.equal(call.params.expected.location[0],0);assert.equal(call.params.transform.location[0],75);});
test('new world scope invalidates the prior draft',async()=>{const h=setup();await h.ready();h.elements.get('location0').value='99';h.subscriptions['showcase.state'](state({scope:'scope2',selectedActorIds:[],actors:[]}));assert.equal(h.elements.get('location0').value,'');assert.equal(h.elements.get('apply').disabled,true);});
test('closed bridge disables native mutations',async()=>{const h=setup();await h.ready();h.subscriptions.backend_error({message:'closed'});assert.equal(h.elements.get('connection').textContent,'DISCONNECTED');assert.equal(h.elements.get('apply').disabled,true);});
test('rapid repeated apply cannot enqueue duplicate UI mutations',async()=>{const h=setup();await h.ready();let resolve;h.setReply(()=>new Promise(r=>resolve=r));h.elements.get('apply').onclick();h.elements.get('apply').onclick();assert.equal(h.calls.filter(c=>c.method==='showcase.setTransform').length,1);resolve(state());await flush();});

function selectedB(){const a=state().actors[0];a.selected=false;return state({selectedActorIds:['opaque-b'],actors:[a,{...a,id:'opaque-b',label:'B',selected:true,transform:{location:[42,0,0],rotation:[0,0,0],scale:[1,1,1]}}]});}
test('pristine draft follows native A-to-B while A remains in history',async()=>{const h=setup();await h.ready();h.subscriptions['showcase.state'](selectedB());assert.equal(h.elements.get('editTitle').textContent,'Transform · B');assert.equal(h.elements.get('location0').value,42);assert.equal(h.elements.get('apply').disabled,false);});
test('dirty A-to-B draft requires explicit keep, reload or discard',async()=>{const h=setup();await h.ready();h.elements.get('location0').value='75';h.elements.get('location0').oninput();h.subscriptions['showcase.state'](selectedB());assert.equal(h.elements.get('location0').value,'75');assert.equal(h.elements.get('apply').disabled,true);assert.equal(h.elements.get('draftChoices').hidden,false);h.elements.get('keepDraft').onclick();assert.equal(h.elements.get('location0').value,'75');h.elements.get('discardDraft').onclick();assert.equal(h.elements.get('location0').value,42);assert.equal(h.elements.get('apply').disabled,false);});
test('pristine deselection and multiselection clear form; dirty deselection preserves disabled draft',async()=>{for(const dirty of [false,true]){const h=setup();await h.ready();if(dirty){h.elements.get('location0').value='33';h.elements.get('location0').oninput();}const next=state({selectedActorIds:[]});next.actors[0].selected=false;h.subscriptions['showcase.state'](next);assert.equal(h.elements.get('location0').value,dirty?'33':'');assert.equal(h.elements.get('apply').disabled,true);}const h=setup();await h.ready();const next=selectedB();next.actors[0].selected=true;next.selectedActorIds=['opaque-a','opaque-b'];h.subscriptions['showcase.state'](next);assert.equal(h.elements.get('location0').value,'');assert.equal(h.elements.get('apply').disabled,true);});
test('new browser generation discards a dirty stale draft',async()=>{const h=setup();await h.ready();h.elements.get('location0').value='99';h.elements.get('location0').oninput();const next=selectedB();next.generation='2';h.subscriptions['showcase.state'](next);assert.equal(h.elements.get('location0').value,42);assert.equal(h.elements.get('draftNotice').hidden,true);});
test('pristine same-actor transform push follows actual host values',async()=>{const h=setup();await h.ready();const next=state();next.actors[0].transform.location[0]=21;h.subscriptions['showcase.state'](next);assert.equal(h.elements.get('location0').value,21);h.setReply(()=>null);h.elements.get('apply').onclick();await flush();assert.equal(h.calls.at(-1).params.expected.location[0],21);});
test('truncated selection never enables a single-actor edit',async()=>{const h=setup();await h.ready();h.subscriptions['showcase.state'](state({selectionTruncated:true,selectedActorCount:129}));assert.equal(h.elements.get('apply').disabled,true);assert.equal(h.elements.get('count').textContent,'129 selected · truncated, edits disabled');});

test('actor drag rejection shows reason, complete count and explicit capacity',async()=>{const h=setup();await h.ready();h.subscriptions['showcase.state'](state({nativeDrag:{kind:'actors',phase:'rejected',reason:'selection_limit',count:0,selectedCount:129,limit:128,hostSeconds:14}}));assert.match(h.elements.get('drag').textContent,/selection_limit/);assert.match(h.elements.get('drag').textContent,/selected 129 \/ limit 128/);assert.match(h.elements.get('drag').textContent,/0 payload item/);});
